name: "Metablock Action"
description: "This action make a deployment to Metablock cloud"
inputs:
  metablock-block-id:
    description: "Metablock Block ID"
    required: true
  metablock-api-token:
    description: "Metablock API Token"
    required: true
  metablock-env:
    description: "Metablock environment for deployment (stage or prod, default is stage)"
  bundle-location:
    description: "Directory containing the bundle to deploy"

outputs:
  preview-url:
    description: "deployment preview URL"
  preview-name:
    description: "deployment preview name"
runs:
  using: "node12"
  main: "dist/index.js"
