name: "Metablock Action"
description: "Make a new deployment into metablock cloud"
inputs:
  token:
    description: "Metablock API token - can be set via the METABLOCK_API_TOKEN env variable"
  block:
    description: "Metablock Block ID - can be set via the METABLOCK_BLOCK_ID env variable"
  bundle:
    description: "Filesystem location of the bundle to deploy"
    default: "./dist"
  env:
    description: "Metablock environment - can be set via the METABLOCK_ENV env variable"
    default: "stage"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - metablock
    - ship
    - ${{ inputs.bundle }}
    - "--token"
    - ${{ inputs.token }}
    - "--block-id"
    - ${{ inputs.block || env.METABLOCK_BLOCK_ID }}
    - "--env"
    - ${{ inputs.env }}
