name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build example
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build example
        run: cd example && yarn && yarn build
      - uses: quantmind/metablock-action@master
        id: metablock-deployment-stage
        if: github.event_name == 'pull_request'
        with:
          metablock-block-id: 7ccced109e374e0ebdcb4d8bb9b8d61e
          metablock-api-token: ${{ secrets.METABLOCK_API_TOKEN }}
          bundle-location: example/public
      - uses: quantmind/metablock-action@master
        id: metablock-deployment-prod
        if: github.event_name == 'push'
        with:
          metablock-block-id: 7ccced109e374e0ebdcb4d8bb9b8d61e
          metablock-api-token: ${{ secrets.METABLOCK_API_TOKEN }}
          metablock-env: prod
          bundle-location: example/public
